    function createUI()
        sc = get(0,'ScreenSize');
        fw = min(1500, sc(3)-80);
        fh = min(920,  sc(4)-100);
        fx = round((sc(3)-fw)/2);
        fy = round((sc(4)-fh)/2);

        app.ui.fig = figure('Name','RAVEN_V1_01 | Master Pipeline | Distilled Intelligence', ...
            'NumberTitle','off','MenuBar','none','ToolBar','none', ...
            'Color',[0 0 0],'Position',[fx fy fw fh], ...
            'Resize','on','CloseRequestFcn',@onClose);

        app.ui.pnlTop = uipanel(app.ui.fig,'Units','normalized','Position',[0.01 0.92 0.98 0.07], ...
            'BackgroundColor',[0 0 0],'ForegroundColor',[0.85 0.95 0.92], ...
            'Title','RAVEN_V1_01 | Master Pipeline | Distilled Intelligence', ...
            'FontWeight','bold');

        app.ui.txtStep = uicontrol(app.ui.pnlTop,'Style','text','Units','normalized', ...
            'Position',[0.01 0.15 0.28 0.70],'String','Step: Idle', ...
            'BackgroundColor',[0 0 0],'ForegroundColor',[0.95 0.95 0.95], ...
            'HorizontalAlignment','left','FontWeight','bold','FontSize',12);
        app.ui.txtStatus = uicontrol(app.ui.pnlTop,'Style','text','Units','normalized', ...
            'Position',[0.30 0.15 0.40 0.70],'String','Status: Ready', ...
            'BackgroundColor',[0 0 0],'ForegroundColor',[0.82 0.95 0.85], ...
            'HorizontalAlignment','left','FontSize',11);
        app.ui.txtError = uicontrol(app.ui.pnlTop,'Style','text','Units','normalized', ...
            'Position',[0.71 0.15 0.28 0.70],'String','Last error: none', ...
            'BackgroundColor',[0 0 0],'ForegroundColor',[1.0 0.75 0.75], ...
            'HorizontalAlignment','left','FontSize',10);

        app.ui.pnlLeft = uipanel(app.ui.fig,'Units','normalized','Position',[0.01 0.08 0.31 0.83], ...
            'Title','Project Setup','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.pnlCenter = uipanel(app.ui.fig,'Units','normalized','Position',[0.33 0.08 0.42 0.83], ...
            'Title','Activity / Results','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.pnlRight = uipanel(app.ui.fig,'Units','normalized','Position',[0.76 0.08 0.23 0.83], ...
            'Title','','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'BorderType','none');
        app.ui.pnlLogo = uipanel(app.ui.pnlRight,'Units','normalized','Position',[0.00 0.56 1.00 0.44], ...
            'Title','','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'BorderType','none');
        app.ui.pnlControls = uipanel(app.ui.pnlRight,'Units','normalized','Position',[0.00 0.00 1.00 0.56], ...
            'Title','Controls','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.pnlBottom = uipanel(app.ui.fig,'Units','normalized','Position',[0.01 0.01 0.98 0.06], ...
            'BackgroundColor',[0 0 0],'BorderType','line','BorderWidth',1);

        curY = 0.95;
        addLabel('Data source (file(s) or folder)', curY);
        app.ui.edData = uicontrol(app.ui.pnlLeft,'Style','edit','Units','normalized', ...
            'Position',[0.03 curY-0.04 0.64 0.045],'String',app.cfg.io.dataSource, ...
            'BackgroundColor',[0.05 0.05 0.05],'ForegroundColor',[0.95 0.95 0.95], ...
            'HorizontalAlignment','left','Callback',@onDataSourceEdited);
        app.ui.btnFolder = uicontrol(app.ui.pnlLeft,'Style','pushbutton','Units','normalized', ...
            'Position',[0.69 curY-0.04 0.13 0.045],'String','Folder','Callback',@onBrowseFolder);
        app.ui.btnMat = uicontrol(app.ui.pnlLeft,'Style','pushbutton','Units','normalized', ...
            'Position',[0.83 curY-0.04 0.13 0.045],'String','File(s)','Callback',@onBrowseMat);
        curY = curY - 0.065;

        addLabel('Uploaded files / classes', curY);
        app.ui.lstFiles = uicontrol(app.ui.pnlLeft,'Style','listbox','Units','normalized', ...
            'Position',[0.03 curY-0.11 0.93 0.095], ...
            'BackgroundColor',[0.03 0.03 0.03],'ForegroundColor',[0.90 0.90 0.90], ...
            'FontName','Consolas','String',{'No files selected'});
        curY = curY - 0.135;

        addLabel('Save folder', curY);
        app.ui.edSave = uicontrol(app.ui.pnlLeft,'Style','edit','Units','normalized', ...
            'Position',[0.03 curY-0.04 0.79 0.045],'String',app.cfg.io.saveBaseDir, ...
            'BackgroundColor',[0.05 0.05 0.05],'ForegroundColor',[0.95 0.95 0.95], ...
            'HorizontalAlignment','left');
        app.ui.btnSave = uicontrol(app.ui.pnlLeft,'Style','pushbutton','Units','normalized', ...
            'Position',[0.83 curY-0.04 0.13 0.045],'String','...','Callback',@onBrowseSave);
        curY = curY - 0.075;

        addLabel('Output root name', curY);
        app.ui.edRoot = uicontrol(app.ui.pnlLeft,'Style','edit','Units','normalized', ...
            'Position',[0.03 curY-0.04 0.93 0.045],'String',app.cfg.io.rootName, ...
            'BackgroundColor',[0.05 0.05 0.05],'ForegroundColor',[0.95 0.95 0.95], ...
            'HorizontalAlignment','left');
        curY = curY - 0.075;

        app.ui.chkAutoDetect = uicontrol(app.ui.pnlLeft,'Style','checkbox','Units','normalized', ...
            'Position',[0.03 curY-0.02 0.50 0.04],'String','Auto-detect groups', ...
            'Value',1,'BackgroundColor',[0 0 0],'ForegroundColor',[0.92 0.92 0.92]);
        app.ui.chkParallel = uicontrol(app.ui.pnlLeft,'Style','checkbox','Units','normalized', ...
            'Position',[0.55 curY-0.02 0.23 0.04],'String','Use parallel', ...
            'Value',0,'BackgroundColor',[0 0 0],'ForegroundColor',[0.92 0.92 0.92]);
        nAvailWorkers = getAvailableWorkerCount();
        app.ui.popWorkers = uicontrol(app.ui.pnlLeft,'Style','popupmenu','Units','normalized', ...
            'Position',[0.79 curY-0.022 0.17 0.045], ...
            'String',arrayfun(@num2str,1:nAvailWorkers,'UniformOutput',false), ...
            'Value',min(max(1,app.cfg.cv.nWorkers),nAvailWorkers), ...
            'BackgroundColor',[0.07 0.07 0.07],'ForegroundColor',[0.95 0.95 0.95], ...
            'TooltipString',sprintf('Available local workers: %d',nAvailWorkers));

        app.ui.pnlDataSummary = uipanel(app.ui.pnlLeft,'Units','normalized','Position',[0.03 0.29 0.93 0.24], ...
            'Title','Dataset Summary','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.lstDatasetSummary = uicontrol(app.ui.pnlDataSummary,'Style','listbox','Units','normalized', ...
            'Position',[0.02 0.03 0.96 0.94], 'BackgroundColor',[0.03 0.03 0.03], ...
            'ForegroundColor',[0.90 0.90 0.90], 'FontName','Consolas', 'Max',2,'Min',0, ...
            'String',{'Dataset: Not loaded'; 'Status: Ready'});

        app.ui.pnlValidation = uipanel(app.ui.pnlLeft,'Units','normalized','Position',[0.03 0.03 0.93 0.23], ...
            'Title','Validation / Readiness','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.lstValidation = uicontrol(app.ui.pnlValidation,'Style','listbox','Units','normalized', ...
            'Position',[0.02 0.03 0.96 0.94], 'BackgroundColor',[0.03 0.03 0.03], ...
            'ForegroundColor',[0.95 0.93 0.78], 'FontName','Consolas', 'Max',2,'Min',0, ...
            'String',{'[OK] Waiting for dataset selection.'});

        app.ui.lstLog = uicontrol(app.ui.pnlCenter,'Style','listbox','Units','normalized', ...
            'Position',[0.03 0.41 0.94 0.56],'BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.82 0.95 0.85],'FontName','Consolas','FontSize',10, ...
            'Max',2,'Min',0,'String',{'RAVEN GUI initialized.'});

        app.ui.pnlRunStatus = uipanel(app.ui.pnlCenter,'Units','normalized','Position',[0.03 0.03 0.94 0.33], ...
            'Title','Live Run Status / Best So Far','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.92 0.92 0.92],'FontWeight','bold');
        app.ui.lstRunStatus = uicontrol(app.ui.pnlRunStatus,'Style','listbox','Units','normalized', ...
            'Position',[0.02 0.03 0.96 0.94], 'BackgroundColor',[0.03 0.03 0.03], ...
            'ForegroundColor',[0.88 0.95 0.98], 'FontName','Consolas', 'Max',2,'Min',0, ...
            'String',{'Current step: Idle'; 'Pipeline status: Ready'; 'Progress: 0.0%'; 'Dataset mode: spectra_blocks'; 'Effective CV mode: stratified'; 'Step 3 mode: full_search'; 'Current dataset: none'; 'Active teacher: none'; 'Active student: none'; 'Last activity: GUI initialized'; 'Last error: none'; 'Best final: pending'; 'Output root: RAVEN_RUN'});

        nCtrlRows = 13;
        btnX = 0.09; btnW = 0.82; btnFS = 10.0;
        btnTop = 0.975; btnBottom = 0.040; btnGap = 0.010;
        btnH = (btnTop - btnBottom - (nCtrlRows-1)*btnGap) / nCtrlRows;
        btnY0 = btnTop - btnH;
        app.ui.btnPreproc = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0 btnW btnH],'String','Preprocessing', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onPreprocPreview);
        app.ui.btnAdvCtrl = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-(btnH+btnGap) btnW btnH],'String','Advanced Settings', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onAdvancedSteps);
        presetY = btnY0-2*(btnH+btnGap);
        pw = 0.255; pg = 0.027; px = 0.09;
        app.ui.btnPresetQuick = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[px presetY pw btnH],'String','Quick', ...
            'FontWeight','bold','FontSize',9.7,'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.95 0.95 0.95],'Callback',@onPresetQuick);
        app.ui.btnPresetAcc = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[px+pw+pg presetY pw btnH],'String','Accurate', ...
            'FontWeight','bold','FontSize',9.7,'BackgroundColor',[0.10 0.22 0.18],'ForegroundColor',[0.92 0.98 0.94],'Callback',@onPresetAccurate);
        app.ui.btnPresetPublish = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[px+2*(pw+pg) presetY pw btnH],'String','Publish', ...
            'FontWeight','bold','FontSize',9.7,'BackgroundColor',[0.22 0.18 0.10],'ForegroundColor',[0.98 0.96 0.90],'Callback',@onPresetPublish);
        app.ui.btnRun = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-3*(btnH+btnGap) btnW btnH],'String','Run Pipeline', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.95 0.95 0.95],'Callback',@onRun);
        app.ui.btnPause = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-4*(btnH+btnGap) btnW btnH],'String','Pause', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onPause);
        app.ui.btnStop = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-5*(btnH+btnGap) btnW btnH],'String','Stop', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.95 0.35 0.35],'Callback',@onStop);
        app.ui.btnBlind = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-6*(btnH+btnGap) btnW btnH],'String','Blind Test', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onBlindTest);
        app.ui.btnOpenOut = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-7*(btnH+btnGap) btnW btnH],'String','Open Output Folder', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onOpenOutput);
        app.ui.btnSaveCfg = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-8*(btnH+btnGap) btnW btnH],'String','Save Config MAT', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onSaveConfig);
        app.ui.btnSaveProj = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-9*(btnH+btnGap) btnW btnH],'String','Save Project', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onSaveProject);
        app.ui.btnLoadProj = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-10*(btnH+btnGap) btnW btnH],'String','Load Project', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onLoadProject);
        app.ui.btnClassMgr = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-11*(btnH+btnGap) btnW btnH],'String','Class Manager', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onClassManager);
        app.ui.btnResultsNav = uicontrol(app.ui.pnlControls,'Style','pushbutton','Units','normalized', ...
            'Position',[btnX btnY0-12*(btnH+btnGap) btnW btnH],'String','Results Navigator', ...
            'FontWeight','bold','FontSize',btnFS,'BackgroundColor',[0.15 0.15 0.15],'ForegroundColor',[0.92 0.92 0.92],'Callback',@onResultsNavigator);

        app.ui.axLogo = axes('Parent',app.ui.pnlLogo,'Units','normalized','Position',[0.04 0.218 0.92 0.782], ...
            'Color',[0 0 0],'XColor',[0 0 0],'YColor',[0 0 0]);
        axis(app.ui.axLogo,'off');

        app.ui.axLicense = axes('Parent',app.ui.pnlLogo,'Units','normalized','Position',[0.02 0.014 0.96 0.188], ...
            'Color',[0 0 0],'XColor',[0 0 0],'YColor',[0 0 0], ...
            'ButtonDownFcn',@onLicenseEmail);
        axis(app.ui.axLicense,'off');
        xlim(app.ui.axLicense,[0 1]); ylim(app.ui.axLicense,[0 1]);
        app.ui.txtLicenseTitle = text(app.ui.axLicense,0.5,0.78,'RAVEN Software License', ...
            'Color',[0.86 0.86 0.86],'FontSize',9.2,'HorizontalAlignment','center', ...
            'FontWeight','bold','HitTest','on','ButtonDownFcn',@onLicenseEmail);
        app.ui.txtLicenseOwner = text(app.ui.axLicense,0.5,0.47,'Registered licensee: Ario Jafari', ...
            'Color',[0.78 0.78 0.78],'FontSize',8.8,'HorizontalAlignment','center', ...
            'FontWeight','bold','HitTest','on','ButtonDownFcn',@onLicenseEmail);
        app.ui.txtLicenseEmail = text(app.ui.axLicense,0.5,0.18,'ario.jafari@liu.se', ...
            'Color',[0.45 0.70 1.00],'FontSize',8.8,'HorizontalAlignment','center', ...
            'HitTest','on','ButtonDownFcn',@onLicenseEmail);

        app.ui.txtProg = uicontrol(app.ui.pnlBottom,'Style','text','Units','normalized', ...
            'Position',[0.01 0.18 0.12 0.64],'String','0.0%','BackgroundColor',[0 0 0], ...
            'ForegroundColor',[0.90 0.90 0.92],'HorizontalAlignment','left','FontWeight','bold','FontSize',12);
        app.ui.progBox = uipanel(app.ui.pnlBottom,'Units','normalized', ...
            'Position',[0.14 0.24 0.83 0.52], 'BackgroundColor',[0.07 0.07 0.07], ...
            'HighlightColor',[0.28 0.28 0.28], 'BorderColor',[0.28 0.28 0.28], ...
            'BorderType','line','BorderWidth',1);
        app.ui.progFill = uipanel(app.ui.progBox,'Units','normalized', ...
            'Position',[0 0 0 1], 'BackgroundColor',[0.12 0.78 0.72], ...
            'BorderType','none');
    end

    function addLabel(txt, y)

        uicontrol(app.ui.pnlLeft,'Style','text','Units','normalized', ...
            'Position',[0.03 min(0.975, y+0.008) 0.93 0.022],'String',txt, ...
            'BackgroundColor',[0 0 0],'ForegroundColor',[0.92 0.92 0.92], ...
            'HorizontalAlignment','left','FontWeight','bold');
    end

    function showLogo()
        cla(app.ui.axLogo);
        axis(app.ui.axLogo,'off');
        logoCoreDir = fileparts(mfilename('fullpath'));
        logoRootDir = fileparts(logoCoreDir);
        candidates = {fullfile(logoCoreDir,'IMG_3820.png'), ...
                      fullfile(logoCoreDir,'IMG_3820.PNG'), ...
                      fullfile(logoRootDir,'IMG_3820.png'), ...
                      fullfile(logoRootDir,'IMG_3820.PNG'), ...
                      fullfile(pwd,'IMG_3820.png'), ...
                      fullfile(pwd,'IMG_3820.PNG'), ...
                      '/mnt/data/inspect_raven/IMG_3820.png', ...
                      '/mnt/data/IMG_3820.png', ...
                      '/mnt/data/IMG_3820.PNG'};
        found = '';
        for i = 1:numel(candidates)
            if exist(candidates{i},'file')
                found = candidates{i};
                break;
            end
        end
        if ~isempty(found)
            I = imread(found);
            image(app.ui.axLogo,I);
            axis(app.ui.axLogo,'image');
            axis(app.ui.axLogo,'off');
            setSummary('Logo', found);
        else
            text(app.ui.axLogo,0.5,0.5,'RAVEN','Color',[0.8 0.95 0.9], ...
                'FontSize',28,'FontWeight','bold','HorizontalAlignment','center');
            text(app.ui.axLogo,0.5,0.40,'Distilled Intelligence','Color',[0.85 0.85 0.6], ...
                'FontSize',12,'HorizontalAlignment','center');
            xlim(app.ui.axLogo,[0 1]); ylim(app.ui.axLogo,[0 1]);
        end
    end

    function onLicenseEmail(~,~)
        emailAddr = 'ario.jafari@liu.se';
        try
            web(['mailto:' emailAddr],'-browser');
        catch
            try
                clipboard('copy',emailAddr);
                msgbox(sprintf('Could not open the default mail client.\nEmail copied to clipboard:\n%s', emailAddr), ...
                    'RAVEN license','help');
            catch
                try
                    logmsg(sprintf('RAVEN license email: %s', emailAddr));
                catch
                    disp(['RAVEN license email: ' emailAddr]);
                end
            end
        end
    end

    function refreshPlan()
        syncCfgFromUI();
        setSummary('Priority','Accuracy -> Stability -> Speed -> Simplicity');
        setSummary('Pipeline','0 Load | 1 kPC/Teacher Baseline | 2 Teacher Search | 3 Student Search | 4 Final + Blind');
        if isfield(app.cfg.preproc,'enabled') && ~app.cfg.preproc.enabled
            setSummary('Preprocessing','RAW only (no SG, no baseline, no normalization; crop still applied)');
        else
            setSummary('Preprocessing',sprintf('SG(%d,%d), AsLS(%.1e, %.1e, %d), Norm=%s, Cosmic=%d', ...
                app.cfg.preproc.sgOrder, app.cfg.preproc.sgFrame, app.cfg.preproc.aslsLambda, ...
                app.cfg.preproc.aslsP, app.cfg.preproc.aslsNIter, app.cfg.preproc.normMode, app.cfg.preproc.cosmicDenoise));
        end
        setSummary('Workers',sprintf('Parallel=%d | Workers=%d', app.cfg.cv.useParallel, app.cfg.cv.nWorkers));
        setSummary('Benchmark', sprintf('Enabled=%d | Methods=%s', double(app.cfg.runtime.runBenchmarks || app.cfg.benchmark.enabled), strjoin(app.cfg.benchmark.methods, ', ')));
        if isfield(app.state,'detectedData') && ~isempty(app.state.detectedData)
            data = app.state.detectedData;
            counts = cellfun(@(b) size(b,2)-1, data.blocks);
            setSummary('Classes',sprintf('%d available', numel(data.groupNames)));
            selNames = getSelectedNamesForValidation(data.groupNames);
            setSummary('Selected Classes',sprintf('%d selected', numel(selNames)));
            setSummary('Spectra',sprintf('Total=%d | Range/class=%d-%d', sum(counts), min(counts), max(counts)));
            xvec = data.blocks{1}(:,1);
            setSummary('Spectral Variables',sprintf('D=%d', numel(xvec)));
            setSummary('Spectral Range',sprintf('%.4g to %.4g', min(xvec), max(xvec)));
        else
            setSummary('Dataset','Not loaded');
        end
        updateValidationPanel();
    end
